name: CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
   
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Run tests with Maven
      run: mvn test

# Build and push to Dockerhub
    - name: Build and Push Docker Image
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: |
          ${{ secrets.DOCKER_HUB_USERNAME }}/shop-app:latest
      # env:
      #   DOCKER_BUILDKIT: 1
      #   DOCKER_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      #   DOCKER_PASSWORD: ${{ secrets.DOCKER_HUB_TOKEN }}
